_BASE_: MinVIS_R50_clip.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_online_clip"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvis_clip"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7

OUTPUT_DIR: './output_DVIS_Online_R50_OVIS_None_clip'