_BASE_: DVIS_Online_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_offline"
  REFINER:
    MASK_AGU: True
    MASK_RATIO: 0.6

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 17
  SAMPLING_FRAME_RANGE: 8
  REVERSE_AGU: True

OUTPUT_DIR: './output_DVIS_Offline_R50_OVIS_AttnMaskAgu'
